### ISSUE TITLE
handle.className.indexOf is undefined if handle is svg element

### ISSUE THREAD

**Issue by makeover** [hjalmers/angular-bootgrid#1]
Im using Highcharts (i.e. SVGs) inside my grids and clicking on them throws an error:
`Uncaught TypeError: handle.className.indexOf is not a function`

Wrapping the SVG inside a div doesnt seem to help.

However, adding a check for SVGs probably would:
`!(handle instanceof SVGElement)`

**Comment by hjalmers** [comment]
Thanks for the feedback, it will be part of next release (after alpha.0)

**Comment by makeover** [comment]
Thanks, but you need to change from:
`handle.className.indexOf('bg-handle') !== -1 && !(handle instanceof SVGElement); `
to:
`!(handle instanceof SVGElement) && handle.className.indexOf('bg-handle') !== -1;`
since otherwise the faulty check would still run.

**Comment by hjalmers** [comment]
You're absolutely right @makeover, just wanted to make sure you were paying attention hehe:P No, seriously thanks for the heads up:)
